"""
Pydantic v2 schemas for the Review Engine.
Defines strict input/output contracts.
"""
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# ── Input Models ───────────────────────────────────────


class FindingInput(BaseModel):
    """A single finding from the scanner pipeline."""
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    vuln_type: str
    severity: str = Field(
        ...,
        pattern=r"^(critical|high|medium|low|info)$",
        description="Finding severity level",
    )
    tool: str = Field(
        ...,
        description="Scanner tool that produced this finding",
    )
    message: str = ""
    cvss_score: Optional[float] = None
    cve_id: Optional[str] = None
    cwe_id: Optional[str] = None
    category: Optional[str] = None
    code_snippet: Optional[str] = None
    fix: Optional[str] = None
    # v2 extensions
    confidence: float = Field(
        1.0,
        ge=0.0,
        le=1.0,
        description="Detection confidence (0.0–1.0)",
    )
    rule_id: Optional[str] = Field(
        None,
        description="Pattern rule ID if from PatternDetector",
    )
    is_synthetic: bool = Field(
        False,
        description="True if generated by PatternDetector",
    )
    # v3 extensions
    tools: list[str] = Field(
        default_factory=list,
        description=(
            "All tools that detected this finding. "
            "Populated by Correlator when multiple "
            "tools agree."
        ),
    )
    status: str = Field(
        "new",
        pattern=r"^(new|existing|fixed)$",
        description=(
            "Finding status: new (introduced in this PR), "
            "existing (pre-existing debt), "
            "fixed (resolved in this PR)"
        ),
    )
    diff_context: Optional[str] = Field(
        None,
        description="Code context from diff or caller",
    )
    change_risk: str = Field(
        "medium",
        pattern=r"^(critical|high|medium|low|none)$",
        description="Per-finding or per-file change risk",
    )


class ReviewRequest(BaseModel):
    """
    Input contract for the Review Engine.
    findings: list of raw scanner findings
    changed_lines: map of file_path → list of changed line numbers
    """
    findings: list[FindingInput] = Field(
        ...,
        min_length=1,
        description="List of scanner findings to review",
    )
    changed_lines: dict[str, list[int]] = Field(
        default_factory=dict,
        description="Map of file_path to changed line numbers",
    )
    # v2 extension
    diffs: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Map of file_path to unified diff string. "
            "Used for pattern detection and context."
        ),
    )
    # v3 extension
    change_risk: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Map of file_path to change risk level. "
            "Values: critical, high, medium, low, none."
        ),
    )


# ── Internal Models ────────────────────────────────────


class RelevanceBucket(str, Enum):
    """Classification of a finding relative to changed lines."""
    RELEVANT = "relevant"
    CONTEXTUAL = "contextual"
    UNRELATED = "unrelated"


class ClassifiedFinding(BaseModel):
    """A finding enriched with relevance and category data."""
    finding: FindingInput
    bucket: RelevanceBucket
    resolved_category: str = "default"
    impact: float = 0.0
    # v2 extensions
    diff_context: Optional[str] = Field(
        None,
        description="Surrounding code context from diff",
    )
    confidence: float = Field(
        1.0,
        description="Effective confidence after scoring",
    )
    is_duplicate: bool = Field(
        False,
        description="True if deduplicated (adjacent-line)",
    )
    # v3 extensions
    corroborated_by: list[str] = Field(
        default_factory=list,
        description="Tools that corroborate this finding",
    )
    corroboration_score: float = Field(
        1.0,
        description="Boost factor from cross-tool agreement",
    )
    status_weight: float = Field(
        1.0,
        description="Weight from finding status",
    )
    change_risk_weight: float = Field(
        1.0,
        description="Weight from file change risk",
    )


class FilteredFindings(BaseModel):
    """Partitioned findings after relevance filtering."""
    relevant: list[ClassifiedFinding] = []
    contextual: list[ClassifiedFinding] = []
    unrelated: list[ClassifiedFinding] = []

    @property
    def all_actionable(self) -> list[ClassifiedFinding]:
        """Relevant + contextual findings (included in review)."""
        return self.relevant + self.contextual

    @property
    def all_classified(self) -> list[ClassifiedFinding]:
        """Every finding regardless of bucket."""
        return self.relevant + self.contextual + self.unrelated


# ── Output Models ──────────────────────────────────────


class ReviewComment(BaseModel):
    """A single file+line review comment."""
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    severity: str
    vuln_type: str
    tool: str
    category: str
    body: str = Field(
        ...,
        description="Rendered comment body (Markdown)",
    )
    impact: float = Field(
        0.0,
        description="Weighted impact score for this finding",
    )
    # v2 extensions
    suggestion: Optional[str] = Field(
        None,
        description="GitHub suggestion block content",
    )
    diff_hunk: Optional[str] = Field(
        None,
        description="Diff hunk context for this comment",
    )
    side: str = Field(
        "RIGHT",
        description="Diff side for GitHub inline comments",
    )
    confidence: float = Field(
        1.0,
        description="Detection confidence",
    )
    rule_id: Optional[str] = Field(
        None,
        description="Pattern rule ID if synthetic",
    )
    # v3 extensions
    status: str = Field(
        "new",
        description="Finding status (new/existing/fixed)",
    )
    corroborated_by: list[str] = Field(
        default_factory=list,
        description="Tools that corroborate this finding",
    )
    change_risk: str = Field(
        "medium",
        description="File change risk level",
    )


class SeverityBreakdown(BaseModel):
    """Score breakdown for a single severity level."""
    severity: str
    emoji: str = ""
    count: int = 0
    impact: float = 0.0


class ToolBreakdown(BaseModel):
    """Score breakdown for a single scanner tool."""
    tool: str
    count: int = 0
    trust: float = 1.0
    contribution: float = 0.0


class ScoreResult(BaseModel):
    """Complete scoring output."""
    total_score: float = 0.0
    max_score: int = 100
    severity_breakdown: list[SeverityBreakdown] = []
    tool_breakdown: list[ToolBreakdown] = []
    # v3 extensions
    new_findings_count: int = Field(
        0, description="Count of new findings",
    )
    existing_findings_count: int = Field(
        0, description="Count of existing findings",
    )
    fixed_findings_count: int = Field(
        0, description="Count of fixed findings",
    )
    correlated_groups: int = Field(
        0, description="Number of cross-tool groups",
    )


class MergeDecision(str, Enum):
    """Possible merge decisions."""
    APPROVE = "approve"
    REQUEST_CHANGES = "request_changes"
    BLOCK = "block"


class DecisionResult(BaseModel):
    """Merge decision with reasoning."""
    decision: MergeDecision
    reasons: list[str] = []
    hard_blockers: list[str] = []
    # v3 extension
    policy_overrides_applied: list[str] = Field(
        default_factory=list,
        description="Policy overrides that fired",
    )


# ── GitHub PR Output Models (v2) ──────────────────────


class GitHubInlineComment(BaseModel):
    """Single inline comment for GitHub PR review API."""
    path: str
    line: int
    side: str = "RIGHT"
    body: str


class GitHubPRReview(BaseModel):
    """
    Formatted output for GitHub PR Review API.
    Can be directly POSTed to:
      POST /repos/{owner}/{repo}/pulls/{pull}/reviews
    """
    event: str = Field(
        ...,
        description="APPROVE | REQUEST_CHANGES | COMMENT",
    )
    body: str = Field(
        ...,
        description="Review summary body (Markdown)",
    )
    comments: list[GitHubInlineComment] = []


class ReviewResult(BaseModel):
    """
    Complete review output — the final product of the engine.
    Contains comments, scoring, merge decision, and summary.
    """
    comments: list[ReviewComment] = []
    score: ScoreResult
    decision: DecisionResult
    summary_markdown: str = ""
    total_findings: int = 0
    relevant_count: int = 0
    contextual_count: int = 0
    unrelated_count: int = 0
    # v2 extensions
    pr_review: Optional[GitHubPRReview] = Field(
        None,
        description="GitHub PR review formatted output",
    )
    pattern_findings_count: int = Field(
        0,
        description="Count of findings from PatternDetector",
    )
    # v3 extensions
    new_findings_count: int = Field(
        0,
        description="Count of new findings in this PR",
    )
    existing_findings_count: int = Field(
        0,
        description="Count of pre-existing findings",
    )
    correlated_groups: int = Field(
        0,
        description="Cross-tool correlated groups",
    )
